### ISSUE TITLE
Create result dir if not exists

### ISSUE THREAD

**Issue by dericdesta** [IPMI-ICNS-UKE/respiratory-motion-prediction#2]
Better code:
```
RESULT_DIR = Path("/datalake/hyperopt")
RESULT_DIR.mkdir(exist_ok=True)
```

**Comment by lukas-wi** [comment]
solved in [5d8022d](https://github.com/IPMI-ICNS-UKE/respiratory-motion-prediction/commit/5d8022df4347719dec7cb30cd92a7745ecb25c91)
